# Generated by Django 5.0.6 on 2024-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
