# Generated by Django 5.0.6 on 2024-07-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travel_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='quantity',
            new_name='capacity',
        ),
    ]
