# Generated by Django 5.0.6 on 2024-07-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='user',
        ),
    ]
