# Generated by Django 5.0.6 on 2024-07-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transectionlog',
            options={'ordering': ('-created',)},
        ),
    ]
